#!/usr/bin/env node
/* ============================================================
   ARTIFACT PREVIEW BUNDLE BUILDER
   Packs the whole multi-page site into a single self-contained
   HTML fragment for the claude.ai artifact preview:
   - every main page (review.html excluded — localStorage-only
     owner tool, useless in a sandboxed iframe) is inlined
     (CSS + JS embedded), base64-encoded, and stored in a shell
   - a postMessage nav shim intercepts internal links so the
     shell can swap pages inside one iframe
   - video <source> tags are stripped (30MB+ media can't ship in
     an artifact); posters become data URIs so players degrade
     to a labeled still
   - Google Fonts links are stripped (artifact CSP blocks all
     external hosts; the font stacks fall back cleanly)

   Usage:  node tools/build-preview.mjs [outDir]
   Emits:  <outDir>/preview-artifact.html  (publish this file —
             body-fragment only, no doctype, per artifact rules)
           <outDir>/preview-local.html     (wrapped copy for
             local browser verification)
   Default outDir: os.tmpdir()/academy-preview
   ============================================================ */

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import os from "node:os";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = process.argv[2] || join(os.tmpdir(), "academy-preview");
mkdirSync(OUT, { recursive: true });

const EXCLUDE = new Set(["review.html"]);
const pages = readdirSync(ROOT).filter(f => f.endsWith(".html") && !EXCLUDE.has(f)).sort();

const css = readFileSync(join(ROOT, "assets/css/style.css"), "utf8");
const jsCache = new Map();
const js = p => {
  if (!jsCache.has(p)) {
    jsCache.set(p, readFileSync(join(ROOT, p), "utf8").replace(/<\/script/gi, "<\\/script"));
  }
  return jsCache.get(p);
};
const dataUri = p =>
  "data:image/jpeg;base64," + readFileSync(join(ROOT, p)).toString("base64");

/* Shim injected into every page: routes internal page links through the
   parent shell, and scrolls to anchors the shell asks for. */
const NAV_SHIM = `<script>
document.addEventListener("click", function (e) {
  var a = e.target.closest ? e.target.closest("a[href]") : null;
  if (!a) return;
  var href = a.getAttribute("href");
  if (href.charAt(0) === "#") {
    // srcdoc iframes navigate away on hash links — scroll locally instead
    e.preventDefault();
    var t = document.getElementById(href.slice(1));
    if (t) t.scrollIntoView({ behavior: "smooth" });
    return;
  }
  if (/^[a-z0-9-]+\\.html(#[\\w-]*)?$/i.test(href)) {
    e.preventDefault();
    parent.postMessage({ academyNav: href }, "*");
  }
}, true);
window.addEventListener("message", function (e) {
  if (e.data && e.data.academyScroll) {
    var t = document.getElementById(e.data.academyScroll.slice(1));
    if (t) t.scrollIntoView();
  }
});
<\/script>`;

function buildPage(name) {
  let html = readFileSync(join(ROOT, name), "utf8");

  // Strip font/preconnect links (CSP blocks external hosts in artifacts)
  html = html.replace(/^<link rel="preconnect".*\n/gm, "");
  html = html.replace(/^<link href="https:\/\/fonts\.googleapis\.com.*\n/gm, "");

  // Inline the stylesheet
  html = html.replace(
    /<link rel="stylesheet" href="assets\/css\/style\.css">/,
    () => `<style>\n${css}\n</style>`
  );

  // Inline every referenced script, preserving order
  html = html.replace(
    /<script src="(assets\/js\/[\w/.-]+\.js)"><\/script>/g,
    (_, p) => `<script>\n${js(p)}\n</script>`
  );

  // Strip video sources (too big for an artifact); posters carry the frame
  html = html.replace(/^\s*<source src="assets\/video\/[\w.-]+" type="video\/\w+">\n?/gm, "");
  html = html.replace(/poster="(assets\/video\/[\w.-]+\.jpg)"/g, (_, p) => `poster="${dataUri(p)}"`);

  // Film key art lives inside inlined JS data strings (poster.art in movies.js),
  // not in src/href attributes — sweep the whole page for those paths too
  html = html.replace(/assets\/img\/film-art\/[\w-]+\.jpg/g, p => dataUri(p));

  // Nav shim last, just inside </body>
  html = html.replace("</body>", NAV_SHIM + "\n</body>");

  const leftover = html.match(/(src|href)="assets\/[^"]+"/g);
  if (leftover) console.warn(`  ⚠ ${name}: unresolved refs ${[...new Set(leftover)].join(", ")}`);
  return html;
}

const bundle = {};
for (const p of pages) {
  bundle[p] = Buffer.from(buildPage(p), "utf8").toString("base64");
  console.log(`packed ${p} (${(bundle[p].length / 1024).toFixed(0)} KB b64)`);
}

const fragment = `<!-- AI Business Academy — artifact preview shell (generated by tools/build-preview.mjs) -->
<title>AI Business Academy — Live Preview</title>
<style>
  html, body { height: 100%; margin: 0; background: #05070f; }
  #academy-frame { border: 0; width: 100%; height: 100vh; display: block; background: #05070f; }
</style>
<iframe id="academy-frame" title="AI Business Academy"></iframe>
<script>
var PAGES = ${JSON.stringify(bundle)};
var frame = document.getElementById("academy-frame");
var pendingHash = "";
function decode(b64) {
  var bin = atob(b64), bytes = new Uint8Array(bin.length);
  for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new TextDecoder().decode(bytes);
}
function show(href) {
  var name = href.split("#")[0] || "index.html";
  pendingHash = href.indexOf("#") >= 0 ? "#" + href.split("#")[1] : "";
  if (!PAGES[name]) return;
  frame.srcdoc = decode(PAGES[name]);
}
frame.addEventListener("load", function () {
  if (pendingHash && frame.contentWindow) {
    frame.contentWindow.postMessage({ academyScroll: pendingHash }, "*");
  }
});
window.addEventListener("message", function (e) {
  if (e.data && e.data.academyNav) show(e.data.academyNav);
});
show("index.html");
</script>`;

writeFileSync(join(OUT, "preview-artifact.html"), fragment);
writeFileSync(
  join(OUT, "preview-local.html"),
  `<!DOCTYPE html>\n<html lang="en"><head><meta charset="UTF-8"><title>Academy preview (local check)</title></head><body>\n${fragment}\n</body></html>`
);

const total = (fragment.length / 1024 / 1024).toFixed(2);
console.log(`\n${pages.length} pages → ${join(OUT, "preview-artifact.html")} (${total} MB)`);
console.log(`local check → ${join(OUT, "preview-local.html")}`);
